export const downloadFile = (content, filename, mimeType = 'text/plain') => {
  try {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    return { success: true };
  } catch (error) {
    return { success: false, error: error.message || 'Download failed' };
  }
};

export const downloadJSON = (data, filename) => {
  const content = typeof data === 'string' ? data : JSON.stringify(data, null, 2);
  const timestamp = getTimestamp();
  const finalFilename = filename || `optimized-prompt-${timestamp}.json`;
  return downloadFile(content, finalFilename, 'application/json');
};

export const downloadTOON = (content, filename) => {
  const timestamp = getTimestamp();
  const finalFilename = filename || `optimized-prompt-${timestamp}.toon`;
  return downloadFile(content, finalFilename, 'text/plain');
};

export const downloadReport = (report, filename) => {
  const timestamp = getTimestamp();
  const finalFilename = filename || `prompt-optimization-report-${timestamp}.md`;
  return downloadFile(report, finalFilename, 'text/markdown');
};

export const generateReport = (originalPrompt, jsonOutput, toonOutput, savings) => {
  const timestamp = new Date().toLocaleString();

  return `# Prompt Optimization Report

**Generated:** ${timestamp}

## Original Prompt

\`\`\`
${originalPrompt}
\`\`\`

**Tokens:** ${savings.original}

---

## Optimized JSON

\`\`\`json
${typeof jsonOutput === 'string' ? jsonOutput : JSON.stringify(jsonOutput, null, 2)}
\`\`\`

**Tokens:** ${savings.json?.optimized || 'N/A'}
**Reduction:** ${savings.json?.percentSaved || 0}%

---

## Optimized TOON

\`\`\`
${toonOutput || 'N/A'}
\`\`\`

**Tokens:** ${savings.toon?.optimized || 'N/A'}
**Reduction:** ${savings.toon?.percentSaved || 0}%

---

## Cost Savings Summary

| Model | Savings per 1K calls | Savings per 100K calls |
|-------|---------------------|------------------------|
${savings.models?.map(m => `| ${m.model} | $${m.per1KCalls} | $${m.per100KCalls} |`).join('\n') || '| N/A | N/A | N/A |'}

---

*Generated by PromptOptimizer*
`;
};

const getTimestamp = () => {
  const now = new Date();
  return now.toISOString().replace(/[:.]/g, '-').slice(0, 19);
};

export const readFileAsText = (file) => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (e) => resolve(e.target.result);
    reader.onerror = (e) => reject(new Error('Failed to read file'));
    reader.readAsText(file);
  });
};
